### ISSUE TITLE
Ability to configure the translation domain

### ISSUE THREAD

**Issue by gremo** [kunicmarko20/SonataAutoConfigureBundle#14]
Offer the ability to configure the translation domain for each admin, or set in using the configuration (for every auto-configured admin).

This way, one can configure the label catalogue **and** translation domain: generally, the are both the same domain.

**Comment by gremo** [comment]
Maybe release 0.4.1? Thanks :)

**Comment by kunicmarko20** [comment]
This will be 0.5.0 because it is a new feature `0.0.X` is only for bugfixes

**Comment by kunicmarko20** [comment]
https://github.com/kunicmarko20/SonataAutoConfigureBundle/releases/tag/0.5.0
