### ISSUE TITLE
Add the ability to configure admin templates

### ISSUE THREAD

**Issue by gremo** [kunicmarko20/SonataAutoConfigureBundle#17]
Right now, since `getTemplates` and `getTemplate($name)` in `AbstractAdmin` re both deprecated, the only way to configure template is using the service definition. Using the annotation, this is a no-sense (just defining a service to change a template).

Templates support can be added this way:

```php
/**
 * @Sonata\AdminOptions(
 *     templates={
 *         "notify": "admin/category/notify.html.twig"
 *     }
 * )
 */
class CategoryAdmin extends AbstractAdmin
{
}
```

**Comment by kunicmarko20** [comment]
Strange thing is that https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/AbstractAdmin.php#L1212 isn't deprecated :thinking: why is the get deprecated then, it could still delegate to registry

**Comment by kunicmarko20** [comment]
cc @greg0ire @OskarStark @core23 anyone remembers?

**Comment by gremo** [comment]
@kunicmarko20 I think `setTemplates` will not be (It's the way to set templates, that will call `TemplateRegistry`). But when reading, we should use `TemplateRegistry` instead.

**Comment by kunicmarko20** [comment]
Seems strange, that setter is still there but getter isn't. I would rather see both there or none.

**Comment by greg0ire** [comment]
I don't remember, sorry… @timobakx, maybe you do?

**Comment by TimoBakx** [comment]
@greg0ire I think there were some users that depended on that method for their system to work and made us revert that specific deprecation.
