### ISSUE TITLE
Default value for adminCode

### ISSUE THREAD

**Issue by jgrygierek** [kunicmarko20/SonataAutoConfigureBundle#24]
Hi, as I see currently default value for `adminCode` option constains path of admin, for example: `App\Admin\UserAdmin`, but according to the docs, it should be something like `admin.user`.

**Comment by kunicmarko20** [comment]
That was changed to support autowiring in Symfony, does it make a problem for you or just docs need to be updated?

**Comment by jgrygierek** [comment]
Docs should be updated.

**Comment by kunicmarko20** [comment]
updated, thank you!
