### ISSUE TITLE
When I try to alias my admin, I get an error

### ISSUE THREAD

**Issue by gremo** [kunicmarko20/SonataAutoConfigureBundle#25]
Maybe I can't understand how Symfony 4 services works, but I want to create an alias (my admin id/code is still `app.admin.experience`):

```yaml
# config/sonata_admin.yaml
# ...
services:
    # service aliases
    App\Admin\ExperienceAdmin: '@app.admin.experience'
```

> You have requested a non-existent service "app.admin.experience".

But, of course exists, and it's auto-configured using this bundle.

**Comment by kunicmarko20** [comment]
Since compiler pass is creating the service, my guess is that the service file configuration is done before it. Can't you just remove the admin code and the id of the service will be the class?

**Comment by gremo** [comment]
Yes I know (I did the PR), but it was just a curiosity 👍

**Comment by kunicmarko20** [comment]
Closing then.
