### ISSUE TITLE
Block management feature?

### ISSUE THREAD

**Issue by gremo** [kunicmarko20/SonataAutoConfigureBundle#27]
Right now, when using this bundle, you can auto-configure admins and extensions. 

What about blocks? Adding blocks is tedious: you need **a service** (at least, you need to specify the `name` argument), you need **a tag** (although you can use `_instance_of`), and, finally, add the block service id under `blocks` in `sonata_block` **configuration**.

**Comment by kunicmarko20** [comment]
Hey @gremo, thanks for this issue but I am not maintaining any of the Sonata packages anymore. I can assist but I don't have time to work on them. If you are interested, I can give you Collaborator permissions and you can take over the package?

**Comment by gremo** [comment]
Hi @kunicmarko20 , sorry for the late response. ATM I'm also so busy at work and in my free time I'm studying Node. I don't have much time to implement the feature I've requested.

So thank you again for offering the collaboration and have a nice day!
