### ISSUE TITLE
Admin without an Entity

### ISSUE THREAD

**Issue by danaki** [kunicmarko20/SonataAutoConfigureBundle#3]
I have an DigestAdmin/DigestController defined which has no corresponding entity. The error I get is following:
```
!!
!!  In AutoConfigureAdminClassesCompilerPass.php line 130:
!!
!!    Entity "Digest" not found, looked in "App\Entity" namespaces.
!!
!!
!!
```

Tried to override the DigestAdmin service with no luck

**Comment by kunicmarko20** [comment]
Yep, this is a bug, will try to fix this tonight.

**Comment by kunicmarko20** [comment]
https://github.com/kunicmarko20/SonataAutoConfigureBundle/releases/tag/0.2.0
