### ISSUE TITLE
What does option "children" do?

### ISSUE THREAD

**Issue by danaki** [kunicmarko20/SonataAutoConfigureBundle#30]
Can't see any effect of it.

**Comment by kunicmarko20** [comment]
Should be https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/child_admin.html, maybe it is not working?

**Comment by danaki** [comment]
Well, it should be better documented I guess.

**Comment by kunicmarko20** [comment]
Be my guest and provide a PR with better documentation. I barely have time for OSS

**Comment by relo-san** [comment]
@kunicmarko20 Now "children" option works not as expected. Method addChild() now not require second argument, but without this argument child admin links only partially. So I suggested PR at #28.

**Comment by danaki** [comment]
Well, I've tested it, option works.

**Comment by danaki** [comment]
However multiple children like:
```
 *     children={
 *         "App\Admin\ProductDescriptionAdmin",
 *         "App\Admin\ProductQuestionAdmin",
 *     }
```

produces strange errors like this:
```
An exception has been thrown during the rendering of a template ("Route pattern "/admin/app/product-paymentsystem/{id}/productquestion/{id}/edit" cannot reference variable name "id" more than once.").
```
