### ISSUE TITLE
sonata_auto_configure.admin.suffix ingored?

### ISSUE THREAD

**Issue by danaki** [kunicmarko20/SonataAutoConfigureBundle#6]
I'm using default config that looks exactly like in README. In my setup I'm using doctrine's inheritance, so my base entity is Product which is abstract and it's descendants like ProductBook, ProductClub etc... So I have an
```
<?php

namespace App\Admin;

use App\Entity\Product\Product;
use Sonata\AdminBundle\Admin\AbstractAdmin;

class ProductAdminBase extends AbstractAdmin
{
...

```
and correspondigly
```
<?php

namespace App\Admin;

use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class ProductBookAdmin extends ProductAdminBase
{
...
```

I'm getting following error:
```
$ bin/console cache:clear

In AutoConfigureAdminClassesCompilerPass.php line 130:

  Entity "ProductAdminBase" not found, looked in "App\Entity" namespaces.
```

I thought `sonata_auto_configure.admin.suffix` is exactly to filter this case that's why I renamed my AbstractProductAdmin to ProductAdminBase but as you see without luck.

**Comment by kunicmarko20** [comment]
Maybe try making `ProductAdminBase` an abstract class? Else it will try to register it as an admin service and it will look for entity

**Comment by kunicmarko20** [comment]
admin suffix basically removes `Admin` from the end of the class name (by default) and tries to find an entity with that name

**Comment by danaki** [comment]
Yes, declaring it abstract did work. May be update README?

**Comment by kunicmarko20** [comment]
What do you think would be useful to add to the README?

**Comment by danaki** [comment]
Like "if you getting 'Entity "ProductAdminBase" not found...' try to make it abstract or smth like that. I really like your bundle, it reduces the number of configs in my project.

**Comment by kunicmarko20** [comment]
Well, if you plan to use your class as a base I guess it should be abstract by default and then symfony wouldn't register it as a service. Not sure if that is useful in the readme, I guess people could find this issue if they run into it again.

Glad you like it, that was to point of it, to make it easier for people. Appreciate all the issues, if you have any suggestion for a feature feel free to open a new issue.
